# Environment config
env:
  # AtariPreprocessing has default frame_skip=4
  env_name : 'BreakoutNoFrameskip-v4'

# Agent config
agent:
  # Learning rate for the agent
  policy_lr : 0.0000625
  # Learning rate for the agent
  value_lr : 0.00000625
  # Bellman equation reward discount
  gamma : 0.99
  # crop shape leave empty for no center cropping
  crop_shape :
  # frame shape full resolution frame would be resized to this size
  input_shape : [84, 84]
  # state size input_shape + [state_size] tensor as enviroment representation
  state_size : 4
  # Number of gradient descent steps to take on value function per epoch.
  value_iter: 10

train:
  # Number of training episodes
  n_train_episodes : 50000
  # Max steps in each episode
  max_steps : 10000
  # model location
  model_dest: /data/experiments/agent-of-atari/05-01-2020-Breakout-v4-vpg
  # save model every save_model steps
  save_model: 500
  # env solved at score
  env_solution: 95

test:
  # Number of testing episodes
  n_test_episodes : 1
  # Max steps in each episode
  max_steps : 10000
  # path where to save played video
  state_dest: /data/experiments/agent-of-atari/05-01-2020-Breakout-v4-vpg/states
