# Environment config
env:
  game_config : 'ddqn/doom/assets/basic.cfg'
  scenario_config : 'ddqn/doom/assets/basic.wad'

# Agent config
agent:
  # Learning rate for the agent
  lr : 0.00025
  # Bellman equation reward discount
  gamma : 0.999
  # maximum exploration likelihood
  max_eps : 0.9
  # minimum exploration likelihood
  min_eps : 0.05
  # exploration likelihood decay
  eps_decay: 1000
  # crop shape leave empty for no center cropping
  crop_shape: [224, 224]
  # frame shape full resolution frame would be resized to this size
  input_shape : [84, 84]
  # state size input_shape + [state_size] tensor as enviroment representation
  state_size : 4
  # memory replay size
  replay_size : 10000

train:
  # Number of training episodes
  n_train_episodes : 1000
  # Max steps in each episode
  max_steps : 100
  # batch size
  batch_size: 64
  # model location
  model_dest: /data/experiments/agent-of-doom/13-12-2019-320x240-basic-ddqn
  # update_target
  update_target: 10
  # save model
  save_model: 100


test:
  # Number of testing episodes
  n_test_episodes : 10
  # Max steps in each episode
  max_steps : 1000
  # path where to save played video
  state_dest: /data/experiments/agent-of-doom/13-12-2019-320x240-basic-ddqn/states
