# Environment config
env:
  game_config : 'dqn/doom/assets/health_gathering.cfg'
  scenario_config : 'dqn/doom/assets/health_gathering.wad'
  rewarded_game_vars : ['health']
  reward_override :
    BASE_REWARD: 0.01
    INJURED: 0.0
    MEDIKIT: 1.0
    DEATH: -5.0

# Agent config
agent:
  # Learning rate for the agent
  lr : 0.00025
  # Bellman equation reward discount
  gamma : 0.99
  # maximum exploration likelihood
  max_eps : 0.9
  # minimum exploration likelihood
  min_eps : 0.1
  # exploration likelihood decay
  eps_decay: 100000
  # crop shape leave empty for no center cropping
  crop_shape:
  # frame shape full resolution frame would be resized to this size
  input_shape : [84, 84]
  # state size input_shape + [state_size] tensor as enviroment representation
  state_size : 4
  # memory replay size
  replay_size : 10000

train:
  # Number of training episodes
  n_train_episodes : 100
  # Max steps in each episode
  max_steps : 2500
  # batch size
  batch_size: 64
  # model location
  model_dest: /data/experiments/agent-of-doom/19-12-2019-320x240-health_gathering-dqn
  # update target every update_target episodes
  update_target: 1000
  # save model every save_model episodes
  save_model: 10000
  # policy update
  policy_update: 4


test:
  # Number of testing episodes
  n_test_episodes : 1
  # Max steps in each episode
  max_steps : 1000
  # path where to save played video
  state_dest: /data/experiments/agent-of-doom/19-12-2019-320x240-health_gathering-dqn/states
