# Environment config
env:
  game_config : 'dqn/doom/assets/basic.cfg'
  scenario_config : 'dqn/doom/assets/basic.wad'

# Agent config
agent:
  # Learning rate for the agent
  lr : 0.00025
  # Bellman equation reward discount
  gamma : 0.999
  # maximum exploration likelihood
  max_eps : 0.9
  # minimum exploration likelihood
  min_eps : 0.05
  # exploration likelihood decay
  eps_decay: 10000
  # crop shape leave empty for no center cropping
  crop_shape: [224, 224]
  # frame shape full resolution frame would be resized to this size
  input_shape : [84, 84]
  # state size input_shape + [state_size] tensor as enviroment representation
  state_size : 4
  # memory replay size
  replay_size : 100000

train:
  # Number of training episodes
  n_train_episodes : 100
  # Max steps in each episode
  max_steps : 1000
  # batch size
  batch_size: 64
  # model location
  model_dest: /data/experiments/agent-of-doom/17-12-2019-320x240-basic-dqn
  # update target every update_target episodes
  update_target: 1000
  # save model every save_model episodes
  save_model: 10000
  # policy update
  policy_update: 4


test:
  # Number of testing episodes
  n_test_episodes : 1
  # Max steps in each episode
  max_steps : 1000
  # path where to save played video
  state_dest: /data/experiments/agent-of-doom/17-12-2019-320x240-basic-dqn/states
