# Environment config
env:
  game_config : 'dqn/doom/assets/simpler_basic.cfg'
  scenario_config : 'dqn/doom/assets/simpler_basic.wad'

# Agent config
agent:
  # Learning rate for the agent
  lr : 0.0002
  # Bellman equation reward discount
  gamma : 0.999
  # maximum exploration likelihood
  max_eps : 0.9
  # minimum exploration likelihood
  min_eps : 0.05
  # exploration likelihood decay
  eps_decay: 1000
  # crop shape
  crop_shape: [224, 224]
  # frame shape
  input_shape : [84, 84]
  # state size input_shape + [state_size] tensor as enviroment representation
  state_size : 4
  # action size
  action_size : 3
  # memory replay size
  replay_size : 10000

train:
  # Number of training episodes
  n_train_episodes : 500
  # Max steps in each episode
  max_steps : 100
  # batch size
  batch_size: 64
  # model location
  model_dest: /data/experiments/agent-of-doom/02-12-2019
  # update_target
  update_target: 10
  # save model
  save_model: 100


test:
  # Number of testing episodes
  n_test_episodes : 100
  # Max steps in each episode
  max_steps : 100
