# Environment config
env:
  type: 'atari'
  name : 'BreakoutNoFrameskip-v4'
  seed: 543

# Agent config
agent:
  # agent type
  agent_type: 'vpg'
  # model type
  model_type: 'convnet-small'
  # Learning rate for the policy net
  policy_lr : 0.0001
  # Learning rate for the value net
  value_lr : 0.00001
  # type of the optimizer
  opt_name: 'adam'
  # norm of gradient clipping, leave empty for no clipping
  grad_clip: 3.0
  # Bellman equation reward discount
  gamma : 0.99
  # crop shape leave empty for no center cropping
  crop_shape:
  # frame shape full resolution frame would be resized to this size
  input_shape : [84, 84]
  # state size input_shape + [state_size] tensor as enviroment representation
  state_size : 4
  # action size
  action_size: 4
  # apply transforms to input state
  input_transforms: ['resize']
  # initalize weights:
  init_weights: true

train:
  # Number of training episodes
  n_train_episodes : 5000
  # Max steps in each episode
  max_steps : 1000
  # model location
  model_dest: /data/experiments/agent-of-atari/13-01-2020-BreakoutNoFrames-vpg
  # save model every save_model episodes
  save_model: 100
  # scenario solved
  env_solution: 100

test:
  # Number of testing episodes
  n_test_episodes : 1
  # Max steps in each episode
  max_steps : 1000
  # path where to save played video
  state_dest: /data/experiments/agent-of-atari/13-01-2020-BreakoutNoFrames-vpg/states
