# Environment config
env:
  # Classic control env name
  env_name : 'CartPole-v0'
  # seed
  seed: 543

# Agent config
agent:
  # Learning rate for the agent
  lr : 0.01
  # Bellman equation reward discount
  gamma : 0.99
  # input shape
  input_shape : [4]
  # state size
  state_size: 1

train:
  # Number of training episodes
  n_train_episodes : 1000
  # Max steps in each episode
  max_steps : 1000
  # model location
  model_dest: /data/experiments/agent-of-control/25-12-2019-CartPole-v0-pg
  # save model every save_model steps
  save_model: 20
  # solution rewards
  env_solution: 195.0

test:
  # Number of testing episodes
  n_test_episodes : 1
  # Max steps in each episode
  max_steps : 10000
  # path where to save played video
  state_dest: /data/experiments/agent-of-control/25-12-2019-CartPole-v0-pg/states
